# Generated by Django 3.1.6 on 2021-02-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='materiales.categoriadematerial', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'categoría de materiales',
                'verbose_name_plural': 'categorías de materiales',
            },
        ),
        migrations.CreateModel(
            name='PrecioDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Precio de material',
                'verbose_name_plural': 'Precios de materiales',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.categoriadematerial')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.unidaddemedida')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
    ]
