# Generated by Django 3.1.6 on 2021-02-17 16:02
# Generated by Django 3.1.6 on 2021-02-17 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import materiales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDePrecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=materiales.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='materiales.categoriadematerial', verbose_name='Categoría')),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_raiz', to='materiales.categoriadematerial', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'categoría de materiales',
                'verbose_name_plural': 'categorías de materiales',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.categoriadematerial', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='PrecioDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=15)),
                ('inicio_de_vigencia', models.DateField(default=datetime.date.today)),
                ('fin_de_vigencia', models.DateField(blank=True, editable=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.unidaddemedida'),
        ),
    ]
