# Generated by Django 3.1.6 on 2021-02-09 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=15)),
                ('inicio_de_vigencia', models.DateField(default=datetime.date.today)),
                ('fin_de_vigencia', models.DateField(blank=True, editable=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
        ),
    ]
