# Generated by Django 3.1.6 on 2021-02-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioDeMaterial',
        ),
    ]
