# Generated by Django 3.1.6 on 2021-02-19 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualizaciondeprecios',
            options={'verbose_name': 'actualización de precios', 'verbose_name_plural': 'actualizaciones de precios'},
        ),
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(default='cod000', max_length=50, verbose_name='código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriadematerial',
            name='categoria_principal',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_raiz', to='materiales.categoriadematerial', verbose_name='Categoría Principal'),
        ),
    ]
