# Generated by Django 3.1.6 on 2021-03-09 16:48

from django.db import migrations, models
import django.db.models.deletion
import materiales.models
import sistema.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario'),
        ('materiales', '0003_auto_20210219_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciodematerial',
            name='ciudad',
            field=models.ForeignKey(default=sistema.models.get_ciudad_default, on_delete=django.db.models.deletion.PROTECT, to='sistema.ciudad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(default=materiales.models.get_categoría_default, on_delete=django.db.models.deletion.PROTECT, to='materiales.categoriadematerial', verbose_name='categoría'),
        ),
    ]
