# Generated by Django 3.1.6 on 2021-05-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizaciondepreciosdeservicios',
            name='actualizados',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='actualizaciondepreciosdeservicios',
            name='creados',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='actualizaciondepreciosdeservicios',
            name='error',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actualizaciondepreciosdeservicios',
            name='lineas',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
