# Generated by Django 3.1.6 on 2021-07-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20210430_0334'),
        ('presupuestos', '0002_auto_20210430_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.ciudad'),
        ),
    ]
