# Generated by Django 3.1.6 on 2021-07-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_auto_20210520_1340'),
        ('presupuestos', '0003_auto_20210704_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalledepresupuesto',
            options={'verbose_name': 'Item de presupuesto', 'verbose_name_plural': 'Items de presupuesto'},
        ),
        migrations.CreateModel(
            name='AdicionalDePresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75, verbose_name='Descripción')),
                ('cantidad', models.FloatField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.presupuesto')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.unidaddemedida')),
            ],
            options={
                'verbose_name': 'Adicional de presupuesto',
                'verbose_name_plural': 'Adicionales de presupuesto',
            },
        ),
    ]
