# Generated by Django 3.1.6 on 2021-03-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'ítem',
                'verbose_name_plural': 'ítems',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioDeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.FloatField(default=1.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de item',
                'verbose_name_plural': 'Servicios del item',
            },
        ),
        migrations.CreateModel(
            name='MaterialDeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.FloatField(default=1.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Material de item',
                'verbose_name_plural': 'Materiales del item',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.rubro'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.unidaddemedida'),
        ),
    ]
