# Generated by Django 3.1.6 on 2021-02-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_delete_preciodematerial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material')),
            ],
            options={
                'verbose_name': 'detalle de ítem',
                'verbose_name_plural': 'detalles de ítem',
            },
        ),
    ]
