# Generated by Django 3.1.6 on 2021-02-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_detalledeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubro',
            options={},
        ),
        migrations.AddField(
            model_name='detalledeitem',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalledeitem',
            name='coeficiente',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='descripción'),
        ),
    ]
