# Generated by Django 3.1.6 on 2021-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20210504_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('vi', 'Vigente'), ('co', 'Concretado'), ('ca', 'Cancelado')], default='vi', max_length=2),
        ),
    ]
