# Generated by Django 3.1.6 on 2021-07-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210520_1954'),
        ('sistema', '0002_auto_20210430_0334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materiales', '0002_auto_20210520_1340'),
        ('cotizaciones', '0004_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDeSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material')),
            ],
            options={
                'verbose_name_plural': 'Materiales de la Solicitud',
            },
        ),
        migrations.CreateModel(
            name='ServicioDeSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios de la Solicitud',
            },
        ),
        migrations.RemoveField(
            model_name='detalledesolicitud',
            name='detalle_de_presupuesto',
        ),
        migrations.RemoveField(
            model_name='detalledesolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='materialdecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='materialdecotizacion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='serviciodecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='serviciodecotizacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema.ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='creado_por',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('vi', 'Vigente'), ('co', 'Concretado'), ('ca', 'Cancelado')], default='vi', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('M', 'Materiales'), ('S', 'Mano de obra')], default='M', editable=False, max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleDeSolicitud',
        ),
        migrations.DeleteModel(
            name='MaterialDeCotizacion',
        ),
        migrations.DeleteModel(
            name='ServicioDeCotizacion',
        ),
        migrations.AddField(
            model_name='serviciodesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.solicitud'),
        ),
        migrations.AddField(
            model_name='materialdesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.solicitud'),
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='profesionales',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='proveedores',
        ),
    ]
