# Generated by Django 3.1.6 on 2021-03-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razón social')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.servicio')),
            ],
        ),
    ]
