# Generated by Django 3.1.6 on 2021-03-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        ('materiales', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razón social')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razón social')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.proveedor')),
            ],
        ),
    ]
